name: check

on:
  push:
  pull_request:

jobs:
  windows-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PowerShell encoding and syntax
        shell: powershell
        run: .\scripts\check.ps1
